qsapp/urls.py
from django.conf.urls import url
from qsapp import views

# app namespace Declaration 
# for URls
app_name = "qsapp"


# url routes tp endpoints
urlpatterns = [

    # Url Route for the index/homepage 
    # mapped with the index view/controller
    url(r'^$', views.index, name="index"),

    # Url Route for the answer Endpoint 
    # mapped with correct_answer view/controller
    url(r'^answer/$', views.correct_answer, name="answer"),

]

question_answer_system/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.conf import settings
from qsapp import views


# main url paths
urlpatterns = [

    # admin panel endpoint
    path('admin/', admin.site.urls),

    # mapping to landing page localhost:8000
    url(r'^$', views.index, name="index"),

    # integreting the app url endpoints
    url(r'^qsapp/', include('qsapp.urls')),

]

# adding the staticfiles endpoints
urlpatterns += (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

qsapp/models.py
from django.db import models
import uuid


# answeres table
class Answers(models.Model):

    # Primary key, auto generated
    recID = models.AutoField(primary_key=True)
    
    # varchar Field max lenth 255
    # blank is allowed
    answer = models.CharField(max_length=255, blank=True)
    
    # atag Unique key with UUID as unique field
    # UUID field is used here
    # unique constraint is True
    # not a editable field
    atag = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    
    # normal TEXT field with blank allowed
    comment = models.TextField(blank=True)

    # auto generated publishing date field
    # generated according to UTC
    pub_date = models.DateTimeField(auto_now_add=True)
    
    # return Answer String 
    # when referenced by default
    def __str__(self):
        return self.answer

#questions table
class Questions(models.Model):

    # Primary key, auto generated
    recID = models.AutoField(primary_key=True)
    
    # varchar Field max lenth 255
    # blank is allowed
    question = models.CharField(max_length=255, blank=True)

    # using the UUIDFIELD from the Answers table 
    # as foreignkey , when a row is deleted
    # cascade (delete corresponding rows in 
    # Answers table too, if all 
    # reference to that answer is deleted)
    atag = models.ForeignKey(Answers, to_field="atag", db_column="atag", on_delete=models.CASCADE)
    
    # auto generated publishing date field
    # generated according to UTC
    pub_date = models.DateTimeField(auto_now_add=True)

    # return Question String 
    # when referenced by default
    def __str__(self):
        return self.question

qsapp/forms.py
from django import forms

# from qsapp.models import Answers

# class AnswersModelForm(forms.ModelForm):

#     class Meta:
#         model = Answers
#         fields = [
#             'answer',
#             'comment'
#         ]

qsapp/views.py
from django.shortcuts import render
from qsapp.models import Answers, Questions
from haystack.query import SearchQuerySet, AutoQuery
from django.db.models import Q


"""
#View / Controller of the project

#Index View
Renderes the homepage with GET 
Request with **qsapp/home.html**
"""

def index(request):
    return render(request, "qsapp/home.html", context={})

"""
#Answer View
Take sthe POST request 
from the HomePage/Index

"""
def correct_answer(request):

    if request.method == "POST":

        """
        **co_if = False** signifies 
        if anything found with Haystack
        """

        co_if = False


        """

         Searches from the database With 
         Haystack API Which Connects 
         with Whoosh Engine

         """
        context_data = SearchQuerySet().autocomplete(content_auto=request.POST.get("question", ""))

        """
        **if len(context_data) == 0:** 
        means nothing found 
        in Haystack Search (unknown words)
        """
        
        if len(context_data) == 0:

            """
            Set **co_if = True** means 
            Haystack Search failed
            Do normal icontains /SQL LIKE 
            search with case insensitive
            """
            
            co_if = True
            """
            Split the words and search ad try match each word 
            """
            search = request.POST.get("question", "")
            
            search = search.split()
            """First Word"""
            db_query = Q(question__icontains=search[0])

            """ALl words with **OR** condition"""
            for term in search[1:]:
                db_query = db_query | Q(question__icontains=term)  

            context_data = Questions.objects.filter(db_query)

    else:
        """Empty context if **GET** REquest"""
        context_data = {}


    """
    Render different templates based 
    """
    """
    if **ONE** data found 
    **len(context_data) == 1**
    """
    """
    If **NO** data found 
    **len(context_data) == 0**
    """
    """
    If **Multiple** data found 
    **len(context_data) > 1**
    """
    if len(context_data) == 1:
        return render(request, "qsapp/answer.html", context={"questions": context_data, "is_empty": False, "co_if": co_if})




    elif  len(context_data) == 0:
        return render(request, "qsapp/answer.html", context={"questions": context_data, "is_empty": True, "co_if": co_if})



    elif len(context_data) > 1:
        return render(request, "qsapp/list_view.html", context={"questions": context_data, "co_if": co_if})

templates/qsapp/answer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

</head>

<body>

    <style>

        body {
        font-family: "IBM Plex Sans", sans-serif;
        background-color: rgba(0,0,0,.1);
        }

        h2 {
        margin: 20px auto 80px;
        font-size: 38px;
        font-weight: 300;
        text-align: center;
        letter-spacing: 2px;
        line-height: 1.5;
        }

        details {
        width: 75%;
        min-height: 5px;
        max-width: 700px;
        padding: 45px 70px 45px 45px;
        margin: 0 auto;
        position: relative;
        font-size: 22px;
        border: 1px solid rgba(0,0,0,.1);
        border-radius: 15px;
        box-sizing: border-box;
        transition: all .3s;
        }

        details + details {
        margin-top: 20px;
        }

        details[open] {
        min-height: 50px;
        background-color: #f6f7f8;
        box-shadow: 2px 2px 20px rgba(0,0,0,.2);
        }

        details p {
        color: #96999d;
        font-weight: 300;
        }

        summary {
        display: flex;
        justify-content: space-between;
        align-items: center;
        font-weight: 500;
        cursor: pointer;
        }

        summary:focus {
        outline: none;
        box-shadow: 0 0 0 4px #f6f7f8, 0 0 0 5px rebeccapurple;
        }

        summary::-webkit-details-marker {
        display: none
        }

        .control-icon {
        fill: rebeccapurple;
        transition: .3s ease;
        pointer-events: none;
        }

        .control-icon-close {
        display: none;
        }

        details[open] .control-icon-close {
        display: initial;
        transition: .3s ease;
        }

        details[open] .control-icon-expand {
        display: none;
        }

        details[open] summary:hover::after {
        animation: pulse 1s ease;
        }

        @keyframes pulse {
        25% {
            transform: scale(1.1);
        }
        50% {
            transform: scale(1);
        }
        75% {
            transform: scale(1.1);
        }
        100% {
            transform: scale(1);
        }
        }

    </style>
    
    <h2>{% if co_if %} {{ questions.0.question }} {% else %} {{ questions.0.object.question }} {% endif %} <a href="{% url 'index' %}">Go Back</a></h2>

    <div style="visibility: hidden; position: absolute; width: 0px; height: 0px;">
      <svg xmlns="http://www.w3.org/2000/svg">
        <symbol viewBox="0 0 24 24" id="expand-more">
          <path d="M16.59 8.59L12 13.17 7.41 8.59 6 10l6 6 6-6z"/><path d="M0 0h24v24H0z" fill="none"/>
        </symbol>
        <symbol viewBox="0 0 24 24" id="close">
          <path d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"/><path d="M0 0h24v24H0z" fill="none"/>
        </symbol>
      </svg>
    </div>

    {% if is_empty %}
        <details open>
        <summary>
          No Data Found
          <svg class="control-icon control-icon-expand" width="24" height="24" role="presentation"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#expand-more" /></svg>
          <svg class="control-icon control-icon-close" width="24" height="24" role="presentation"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#close" /></svg>
        </summary>
        <p>No Data.</p>
      </details>
    {% else %}
    
        {% for item in questions %}

            {% if co_if %}
                <details open>
                    <summary>
                        {{ item.atag.answer }}
                      <svg class="control-icon control-icon-expand" width="24" height="24" role="presentation"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#expand-more" /></svg>
                      <svg class="control-icon control-icon-close" width="24" height="24" role="presentation"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#close" /></svg>
                    </summary>
                    <p>{{ item.atag.comment }}</p>
                  </details>

            {% else %}

                <details open>
                <summary>
                    {{ item.object.atag.answer }}
                  <svg class="control-icon control-icon-expand" width="24" height="24" role="presentation"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#expand-more" /></svg>
                  <svg class="control-icon control-icon-close" width="24" height="24" role="presentation"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#close" /></svg>
                </summary>
                <p>{{ item.object.atag.comment }}</p>
              </details>

                
            {% endif %}
        
        {% endfor %}

    {% endif %}


</body>

</html>

templates/qsapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} Question Answer Site {% endblock title %}</title>
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
      .green-class {
        color: green;
      }
      .red-class {
        color: red;
      }
      .grey-class {
        color: grey;
      }

    </style>

  </head>
  <body>
    
    <div class="container">

        {% block body %}
            
        {% endblock body %}
    </div>
    


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    {% block script %} {% endblock script %}
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

  </body>
</html>

templates/qsapp/home.html
{% extends "qsapp/base.html" %}

{% block title %} {{ block.super }} | List {% endblock title %}

{% block script %}

<style>
    /* JUST FOR THIS DEMO */
    html,body{ height:100%; }
    body{ 
        background: url("/static/qsapp/images/o.jpg") no-repeat center center fixed; 
        display:flex; 
        align-items:center; 
    }


    .searchForm input[type=submit]:hover {
        background-color: firebrick;
    }

    .searchForm *{  
        display: block;
        box-sizing: padding-box;
        overflow: hidden;

        padding: 10px;
        width: 250px;
        font-size: 14px;
        margin: 50px auto;
        border-radius: 6px;
        box-shadow: 2px 2px 8px rgba(black, .3);
        border: 0;
    }

    #adminpanel:hover {
        background-color: firebrick;
    }

    #adminpanel {
        display: block;
        box-sizing: padding-box;
        overflow: hidden;

        padding: 10px;
        width: 250px;
        font-size: 14px;
        margin: 50px auto;
        border-radius: 6px;
        box-shadow: 2px 2px 8px rgba(black, .3);
        border: 0;
    }

</style>

<script>

    var charStart = 140;
    var charsCurrent = 0;

    $(".searchForm").append("<span id='charsleft'>Chars Left : "+ charStart +"</span>");

    $(".searchForm textarea").keyup(function (event) {
        //console.log(event.key, event.keyCode, event.timeStamp);
        var tVal = $(this).val();
        charsCurrent = charStart - tVal.length;
        var spanText = $("#charsleft");
        spanText.text("Chars Left : "+charsCurrent);
        
        if (charsCurrent === 0){
            spanText.removeClass("red-class");
            spanText.removeClass("green-class");
            spanText.addClass("grey-class");
        }
        else if (charsCurrent > 0){
            spanText.removeClass("red-class");
            spanText.removeClass("grey-class");
            spanText.addClass("green-class");
        } else if (charsCurrent < 0){
            spanText.removeClass("grey-class");
            spanText.removeClass("green-class");
            spanText.addClass("red-class");
        }
    });


    $(document)
    .one('focus.autoExpand', 'textarea.autoExpand', function(){
        var savedValue = this.value;
        this.value = '';
        this.baseScrollHeight = this.scrollHeight;
        this.value = savedValue;
    })
    .on('input.autoExpand', 'textarea.autoExpand', function(){
        var minRows = this.getAttribute('data-min-rows')|0, rows;
        this.rows = minRows;
        rows = Math.ceil((this.scrollHeight - this.baseScrollHeight) / 16);
        this.rows = minRows + rows;
    });
    
</script>

{% endblock script %}

{% block body %}
<div class="container hold">

    <div class="jumbotron">
        
        <a id="adminpanel" class="btn btn-success" href="{% url 'admin:index' %}">Admin Panel</a>

        <form class="searchForm" action="{% url 'qsapp:answer' %}" method="POST">
            {% csrf_token %}
        
            <textarea class='autoExpand' rows='3' data-min-rows='3' name="question" placeholder='Your Question'></textarea>
            <input class="btn btn-primary" type="submit" value="Ask">
        
        </form>
    </div>

</div>


{% endblock body %}

templates/qsapp/list_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

</head>

<body>

    <style>

        body {
        font-family: "IBM Plex Sans", sans-serif;
        background-color: rgba(0,0,0,.1);
        }

        h2 {
        margin: 20px auto 80px;
        font-size: 38px;
        font-weight: 300;
        text-align: center;
        letter-spacing: 2px;
        line-height: 1.5;
        }

        details {
        width: 75%;
        min-height: 5px;
        max-width: 700px;
        padding: 45px 70px 45px 45px;
        margin: 0 auto;
        position: relative;
        font-size: 22px;
        border: 1px solid rgba(0,0,0,.1);
        border-radius: 15px;
        box-sizing: border-box;
        transition: all .3s;
        }

        details + details {
        margin-top: 20px;
        }

        details[open] {
        min-height: 50px;
        background-color: #f6f7f8;
        box-shadow: 2px 2px 20px rgba(0,0,0,.2);
        }

        details p {
        color: #96999d;
        font-weight: 300;
        }

        summary {
        display: flex;
        justify-content: space-between;
        align-items: center;
        font-weight: 500;
        cursor: pointer;
        }

        summary:focus {
        outline: none;
        box-shadow: 0 0 0 4px #f6f7f8, 0 0 0 5px rebeccapurple;
        }

        summary::-webkit-details-marker {
        display: none
        }

        .control-icon {
        fill: rebeccapurple;
        transition: .3s ease;
        pointer-events: none;
        }

        .control-icon-close {
        display: none;
        }

        details[open] .control-icon-close {
        display: initial;
        transition: .3s ease;
        }

        details[open] .control-icon-expand {
        display: none;
        }

        details[open] summary:hover::after {
        animation: pulse 1s ease;
        }

        @keyframes pulse {
        25% {
            transform: scale(1.1);
        }
        50% {
            transform: scale(1);
        }
        75% {
            transform: scale(1.1);
        }
        100% {
            transform: scale(1);
        }
        }

    </style>
    
    <h2>Multiple Answers Found <a href="{% url 'index' %}">Go Back</a></h2>

    <div style="visibility: hidden; position: absolute; width: 0px; height: 0px;">
      <svg xmlns="http://www.w3.org/2000/svg">
        <symbol viewBox="0 0 24 24" id="expand-more">
          <path d="M16.59 8.59L12 13.17 7.41 8.59 6 10l6 6 6-6z"/><path d="M0 0h24v24H0z" fill="none"/>
        </symbol>
        <symbol viewBox="0 0 24 24" id="close">
          <path d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"/><path d="M0 0h24v24H0z" fill="none"/>
        </symbol>
      </svg>
    </div>

    {% if is_empty %}
        <details open>
        <summary>
          No Data Found
          <svg class="control-icon control-icon-expand" width="24" height="24" role="presentation"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#expand-more" /></svg>
          <svg class="control-icon control-icon-close" width="24" height="24" role="presentation"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#close" /></svg>
        </summary>
        <p>No Data.</p>
      </details>
    {% else %}
      
        {% for item in questions %}

            {% if co_if %}
                <details open>
                    <summary>
                        {{ item.atag.answer }}
                      <svg class="control-icon control-icon-expand" width="24" height="24" role="presentation"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#expand-more" /></svg>
                      <svg class="control-icon control-icon-close" width="24" height="24" role="presentation"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#close" /></svg>
                    </summary>
                    <p>{{ item.atag.comment }}</p>
                    <p>Question: {{ item.question }}</p>
                  </details>

            {% else %}

                <details open>
                <summary>
                    {{ item.object.atag.answer }}
                  <svg class="control-icon control-icon-expand" width="24" height="24" role="presentation"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#expand-more" /></svg>
                  <svg class="control-icon control-icon-close" width="24" height="24" role="presentation"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#close" /></svg>
                </summary>
                <p>{{ item.object.atag.comment }}</p>
                <p>Question:  {{ item.object.question }}</p>
              </details>

                
            {% endif %}
        
        {% endfor %}

    {% endif %}


</body>

</html>